to check numpy is instaled or not

In [1]:
!pip install numpy
import numpy as np

if not then :   pip install numpy
####Now, 
to import and use numpy library,<br>
np == numpy

In [ ]:
import numpy as np

#creating numpy array:

In [ ]:
ar=np.array([1,2,3,4])
ar

NameError: ignored

or, 
### if we make a nested array: then,


In [ ]:
python_list=[[1,2,3,4],[6,7,8,9]]
arr=np.array(python_list)
arr

NameError: ignored

here the out put will be like a matrix <br>
####Now,<br>
'arange' a function in numpy libreries. <br>
it usded to make numpy array in a range of numbers.<br>
now, arange has 3 parameters.<br>
(start,end, step_size) <br>
if step size is not given the default is 1<br>

In [29]:
arrr=np.arange(0,10,2)
arrr

array([0, 2, 4, 6, 8])

যদি  এমন একটা matrix বানাতে হই যেখানে matrix এর সব ০ তাহলে, function আছে, 'zeros' যেখানে ২ টা parameter আছে. parameter হিসেবে যদি ১টা নাম্বার দেই, যেমন ৫, তাহলে সুধু ৫টা ০ দিয়ে row matrix বানাবে<br>

যদি ২টা parameter ইই দেই তবে ১ম টা row , পরের টা column<br>
তবে ২তাইই ((row, column )) double ব্রাকেট এর মদ্ধে থাকবে।

In [ ]:
print(np.zeros(5))
print()
np.zeros((3,4))

[0. 0. 0. 0. 0.]



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

তবে এখানে সব floating point এ আছে।<br>
ইন্তেগের করতে হোলে<br>
np.zeros((4,3),dtype="int" )


In [ ]:
print (np.zeros(5,dtype="int" ))
print()
np.zeros((4,3),dtype="int" )

[0 0 0 0 0]



array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

এখন,
'zeros' এর মত 'ones' একটা function আছে।

In [ ]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

আরেক টা function আছে 'full'<br>
np.full((row,column), 10)<br>
তাহলে  row, column সব ১০ দারা fill হবে<br>


In [ ]:
np.full((3,4), 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

identity matrix:
<br>
eye(row)<br>


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

এখন একটি গুরুত্তপুরন function:
<br>
<strong>'linspace'</strong>
<br>
np.linspace(start,end, divide)
এখানে start= 0 হোলে এবং end=10 হোলে এবং divide=5 হোলে,<br>
০ থেকে ১০ এর মধ্যে ৫ ভাগে ভাগ হয়ে <br>
[0. , 2.5 , 5. , 7.5 , 10. ]
<br>
বেপারটা এমন যে,<br>
একটা সরল রেখা আক্তে হবে যার স্থানাঙ্ক ০ থেকে ১০
<br>
এখন এর মধ্যে সমান ৫ টা পয়েন্ট বের করতে হবে। তাহলে point গুলা হবে ঃ <br>
np.linspace(০,১০,৫) <br>
[0. , 2.5 , 5. , 7.5 , 10. ]<br>



In [ ]:
np.linspace(0,10,7) 

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

এবার log_space দিয়ে evenly distribution
<br> <strong> 'logspace' function</strong><br>
'linspace' এর মতইই just extra একটা পারামেটার আছে function  এ , 'base' <br>
যেটা , result কত base Log দেখতে চাচ্ছি তা নির্দেশ করে or, exp এও দেখা যাবে<br>
আর এই পারামেটার ছাড়া হোলে by default base 10 এএ দেখাবে
<br><br>
np.logspace(0,10,5) # here,(log_base 10) base =10<br>
np.logspace(0,10,5, base =2) # here,(log_base 2) base =2<br>
np.logspace(0,10,5, base =np.e ) # here,(log_base epsilon) base =epsilon<br><br>

In [ ]:
np.logspace(0,10,7, base= 2)

array([1.00000000e+00, 3.17480210e+00, 1.00793684e+01, 3.20000000e+01,
       1.01593667e+02, 3.22539789e+02, 1.02400000e+03])

<strong> diagonal matrix making function 'diag':</strong><br>

In [ ]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

random number generating function<br>
np.random.rand(4) #1d matrix<br>
np.random.rand(4,3) #2d matrix<br>
np.random.rand(4,4,4) #3d matrix<br>

In [ ]:
print(np.random.rand(4)) #1d matrix
print("")
print("")
print(np.random.rand(2,2)) #2d matrix
print("")
print("")
print(np.random.rand(2,2,2)) #3d matrix)
print("")
print("")

[0.47174969 0.61137453 0.50886639 0.36165707]


[[0.55637462 0.30024987]
 [0.4895491  0.73093113]]


[[[0.7173619  0.61072548]
  [0.93320895 0.89540955]]

 [[0.41259348 0.95140771]
  [0.50621412 0.76924433]]]




<strong> make array of random integer numbers:</strong><br>
<br> sample:<br>
np.random.randint(lower limit,lower limit +1 ,কয় টা সংখ্যা লাগবে )
<br> np.random.randint(0,10,10 ) <br>

In [ ]:
np.random.randint(0,10,10 )

array([6, 3, 3, 4, 1, 1, 4, 8, 1, 1])

In [5]:
arr=np.random.randint(0,10,(2,5) )
arr

array([[4, 4, 8, 5, 0],
       [4, 3, 8, 9, 7]])

## now
we can reshape the matrix.
reshape()

In [6]:
arr=np.random.randint(0,10,10 )
arr # first making a 1d matrix

array([8, 9, 1, 6, 0, 8, 7, 0, 1, 2])

In [7]:
#re shape the array

arr.reshape(2,5)


array([[8, 9, 1, 6, 0],
       [8, 7, 0, 1, 2]])

## or 

In [10]:
arr=np.random.randint(0,10,(4,3) )
print(arr) # first making a 1d matrix
#re shape the array
print() 
print() 
arr= arr.reshape(2,6)
print(arr) 

[[7 6 0]
 [9 1 9]
 [4 8 2]
 [8 2 6]]


[[7 6 0 9 1 9]
 [4 8 2 8 2 6]]


more use of re shape or reshape 

In [56]:
arr = np.arange(1,13).reshape(4,3)
arr2 = np.arange(1,13).reshape(4,3)

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### এখন matrix এর মধ্যে ম্যাক্সিমাম value or minumum value or একটা range এর মধ্যে কি কি value আছেঃ
<br>

In [33]:
####code:
arr=np.random.randint(0,10,(2,6) ) # making a random matrix
print(arr)
print()
print ('max: ',arr.max()) #finds maximum number in the array
print ('index :' ,arr.argmax()) #finds the index of maximum number in the array
print("",end="\n\n")

print ('min: ',arr.min()) #finds min number in the array
print ('index :' ,arr.argmin()) #finds the index of mim number in the array


[[0 6 7 8 4 5]
 [0 9 0 2 8 2]]

max:  9
index : 7


min:  0
index : 0


In [36]:
arr= np.arange(0,25) # making a 1d random matrix
print(arr)
arr.max() #finds maximum number in the array
print (arr.argmax()) #finds the index of maximum number in the array
print ('index :' ,arr.argmax()) #finds the index of maximum number in the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
24
index : 24


## matrix shape finding

In [42]:
arr=np.random.randint(0,10,(2,6) ) # making a random matrix<br>
arr.shape ## shape finding<br>

arr.ndim  #কয় dimention array(1d,2d,3d)?<br>

arr.size  #total elements<br>


12

### data type of a matrix elements

In [45]:
arr=np.random.randint(0,10,(2,6) )
arr.dtype
arr=np.random.rand(2,6)
arr.dtype

dtype('float64')

### arr2 = arr 

এটা copy হই না । address pass হই

## selection (select a part of a matrix and make sub matrix):

In [49]:
arr=np.random.randint(0,10,(5,7) )
print(arr)
print()
arr[:2,1:]

[[6 5 2 0 0 4 2]
 [4 8 8 5 7 6 2]
 [4 7 7 8 6 2 0]
 [5 0 7 6 3 2 0]
 [0 4 5 9 7 5 2]]



array([[5, 2, 0, 0, 4, 2],
       [8, 8, 5, 7, 6, 2]])

## selection (conditional selection):

In [54]:
arr=np.random.randint(0,10,(5,7) )
print(arr)
print()
print(arr>4)
print()
print(arr[arr>4])


[[5 0 0 4 7 9 6]
 [6 3 1 3 4 1 9]
 [8 2 7 3 1 9 0]
 [9 8 0 9 4 7 8]
 [7 9 4 6 1 7 7]]
[[ True False False False  True  True  True]
 [ True False False False False False  True]
 [ True False  True False False  True False]
 [ True  True False  True False  True  True]
 [ True  True False  True False  True  True]]

[5 7 9 6 6 9 8 7 9 9 8 9 7 8 7 9 6 7 7]



### here we can find the all function about numpy arithmatic operations: 
<a src="## https://docs.scipy.org/doc/numpy/reference/ufuncs.html">## https://docs.scipy.org/doc/numpy/reference/ufuncs.html </a>

arethmatic sum of 2 matrix

In [55]:
arr=np.random.randint(0,10,(5,7) )
print(arr)
print()
print(arr+arr)

[[5 7 9 6 1 7 3]
 [3 4 5 3 3 3 5]
 [3 1 0 9 1 3 7]
 [5 6 8 9 0 4 3]
 [6 5 2 9 4 0 2]]

[[10 14 18 12  2 14  6]
 [ 6  8 10  6  6  6 10]
 [ 6  2  0 18  2  6 14]
 [10 12 16 18  0  8  6]
 [12 10  4 18  8  0  4]]


In [59]:
arr = np.arange(1,13).reshape(4,3)
arr2 = np.arange(0,12).reshape(4,3)

print(arr/arr2)

[[       inf 2.         1.5       ]
 [1.33333333 1.25       1.2       ]
 [1.16666667 1.14285714 1.125     ]
 [1.11111111 1.1        1.09090909]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
